routes/user.py
from flask import Blueprint, render_template, request, jsonify, session
from werkzeug.security import generate_password_hash
from models.user import User
from werkzeug.exceptions import BadRequest, UnsupportedMediaType
from config.db import db

user = Blueprint('user', __name__)

def require_content_type(content_type):
    def decorator(f):
        def wrapper(*args, **kwargs):
            if request.mimetype != content_type:
                print(request.mimetype)
                raise UnsupportedMediaType(description=f"Tipo de contenido no admitido. Se esperaba {content_type}")
            return f(*args, **kwargs)
        return wrapper
    return decorator

@user.route('/user/new', methods=['GET', 'POST'])
def new_user():
    if request.method == 'GET':
        return render_template('sign_up.html')
    else:
        user_data = request.get_json()
        try:
            if user_data['password'] != user_data['confirm-password']:
                return jsonify('Las contraseñas no coinciden')
            else:
                if 'AE' in user_data:
                    type_employee = user_data['AE']
                elif 'ET' in user_data:
                    type_employee = user_data['ET']
                else:
                    type_employee = None

                if type_employee is None:
                    return jsonify('Falta tipo de empleado')
                else:
                    username = type_employee + str(user_data['num_employee'])
                    first_name = user_data['first_name']
                    last_name = user_data['last_name']
                    password = generate_password_hash(user_data['password'], method='pbkdf2:sha256')
                    email = user_data['email']
                    role = user_data['role']
                    campaign = user_data['campaign']
                    full_name = f"{first_name} {last_name}"

                    new_user = User(full_name, username, email, password, role, campaign)

                    db.session.add(new_user)
                    db.session.commit()

                    return jsonify(f'Usuario  {username} creado exitosamente')
        except Exception as e:
            return jsonify(f'Ha ocurrido un error: {e}')

@user.route('/user/edit/<id>', methods=['GET','POST'])
def edit_user(id):
    user = User.query.get(id)
    if request.method == 'GET':
        first_name ,last_name = str(user.full_name).split(" ")
        usuario = {
            'id':int(user.id),
            'username': str(user.username),
            'first_name':first_name,
            'last_name':last_name,
            'email': str(user.email),
            'role':str(user.role_id),
            'campaign':str(user.campaign_id),
            'password': str(user.password)
        }
        return render_template('edit_user.html', usuario=usuario)
    else:
        user_data = request.get_json

        pass
    

@user.route('/user/delete/<id>')
def delete_user(id):
    try:
        user = User.query.get(id)
        if user:
            db.session.delete(user)
            db.session.commit()
            return f'Se ha eliminado el usuario {user.username}'
        else:
            return f'No se ha encontrado ningún usuario con ID {id}'
    except Exception as e:
        return jsonify({f'Ha ocurrido un error: {e}'})


@user.route('/user/users')
def get_users():
    try:
        usuarios = User.query.all()
        return render_template('get_users.html', usuarios=usuarios)
    except Exception as e:
        return jsonify({f'Ha ocurrido un error: {e}'})

templates/edit_user.html
{%extends 'layout.html'%}

{% block head %}
    {% block tittle %}
    <title>Edit User</title>
    {% endblock %}
    <!--Link boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
    <!--Boostrap customizado-->
    {%block styles%}
        <link rel="stylesheet" href="{{url_for('css', filename='styles_logo.css')}}">
    {%endblock%}
{% endblock %}

{%block main%}

<div class="container-fluid d-flex">

    <div class="row w-100 justify-content-evenly align-items-center">
        <div class="col-lg-8">
            <h2 class="text-primary text-center">Edit user</h2>
            <form id="form_signup" class="" action="/user/edit/{{usuario.id}}">
                
                <div class="input-group my-1">
                    <span class="input-group-text" id="addon-wrapping">
                        <img src=" {{url_for('img', filename='employee_icon.svg')}} " alt="">
                    </span>
                    <input id="num_employee" name="num_employee" type="text" class="form-control"
                        placeholder="N° Employee" aria-label="id" aria-describedby="addon-wrapping"
                        data-tipo="num_employee" pattern="[0-9]" required minlength="5" maxlength="7"
                        value="{{ usuario.username }}" disabled>
                    <label for="num_employee"></label>
                    <span class="error-false"></span>
                </div>

                <div class="input-group my-1">
                    <span class="input-group-text" id="addon-wrapping">
                        <img src="{{url_for('img', filename='name_icon.svg')}}" alt="">
                    </span>
                    <input id="first_name" name="first_name" type="text" class="form-control input-signup"
                        placeholder="First Name" aria-label="first_name" aria-describedby="addon-wrapping"
                        data-tipo="first_name" required minlength="3" maxlength="25"
                        value="{{ usuario.first_name }}">
                    <label for="first_name"></label>
                    <span class="error-false"></span>
                </div>

                <div class="input-group my-1">
                    <span class="input-group-text" id="addon-wrapping">
                        <img src="{{url_for('img', filename='name_icon.svg')}}" alt="">
                    </span>
                    <input id="last_name" name="last_name" type="text" class="form-control input-signup"
                        placeholder="Last Name" aria-label="last_name" aria-describedby="addon-wrapping"
                        data-tipo="last_name" required minlength="3" maxlength="25"
                        value="{{ usuario.last_name }}">
                    <label for="last_name"></label>
                    <span class="error-false"></span>
                </div>

                <div class="input-group my-1">
                    <span class="input-group-text" id="addon-wrapping">
                        <img src=" {{url_for('img', filename='user_icon.svg')}} " alt="">
                    </span>
                    <input id="email" name="email" type="email" class="form-control input-login"
                        placeholder="Email@example.com" aria-label="email" aria-describedby="addon-wrapping"
                        data-tipo="email" required
                        value="{{ usuario.email }}">
                    <label for="email"></label>
                    <span class="error-false"></span>
                </div>

                
                <div class="form-floating my-1">
                    <select id="campaign" name="campaign" class="form-select input-signup" data-tipo="campaign"
                        required>
                        <option disabled>Select a campaign</option>
                        <option value="1">UP</option>
                        <option value="2">ATH Movil</option>
                        <option value="3">Place to Pay</option>
                    </select>
                    <label for="campaign">Campaign</label>
                </div>
                
                <div class="form-floating my-1">
                    <select id="role" name="role" class="form-select input-signup" data-tipo="role" required>
                        <option disabled>Select a role</option>
                        <option value="1">Analyst</option>
                        <option value="2">Supervisor</option>
                    </select>
                    <label for="role">Role</label>
                </div>
                
                <hr>

                <div class="form-btn d-flex justify-content-end">
                    <button id="submit_login" class="btn btn-primary" type="submit" disabled>Create User</button>
                </div>

            </form>

        </div>
    </div>

</div>

{%endblock%}
{{super()}}

templates/get_users.html
{% extends 'layout.html' %}

{% block head %}
    {% block tittle %}
    <title>Get User</title>
    {% endblock %}
    <!--Link boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
    <!--Boostrap customizado-->
    {%block styles%}
        <link rel="stylesheet" href="{{url_for('css', filename='styles_logo.css')}}">
    {%endblock%}
{% endblock %}

{% block main %}

<div class="container-fluid">

    <div class="row w-100">

        <div class="col-lg-12">

            <h2 class="text-primary text-center">Usuarios</h2>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">Num Empleado</th>
                        <th class="text-center" scope="col">Nombre Completo</th>
                        <th class="text-center" scope="col">Email</th>
                        <th class="text-center" scope="col">Rol</th>
                        <th class="text-center" scope="col">Campaña</th>
                        <th class="text-center" scope="col">Editar</th>
                        <th class="text-center" scope="col">Eliminar</th>
                    </tr>
                </thead>

                <tbody>
                {% for usuario in usuarios %}
                    <tr class="">
                        <th class="text-center" scope="row">{{ usuario.username }}</th>
                        <td class="text-center">{{ usuario.full_name }}</td>
                        <td class="text-center">{{ usuario.email }}</td>
                        <td class="text-center">{{ usuario.role }}</td>
                        <td class="text-center">{{ usuario.campaign }}</td>
                        <td class="text-center"> 
                            <a class="btn btn-warning" href=' {{url_for("user.edit_user", id=usuario.id)}} '>
                                <img src="{{ url_for('img', filename='edit.svg')}}" alt="edit">
                            </a>
                        </td>
                        <td class="text-center">
                            
                            <a class="btn btn-danger h-75" href='{{url_for("user.delete_user", id=usuario.id)}}'>
                                <img src="{{ url_for('img', filename='delete.svg')}}" alt="delete">
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

{{ super() }}

templates/index.html
{% extends 'layout.html' %}

{% block head %}

{%block tittle%}
<title>My Tickets</title>
{%endblock%}

{%block styles%}
<link rel="stylesheet" href="{{url_for('css', filename='styles_dashboard.css')}}">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
{%endblock%}
{% endblock %}

{%block navbar%}

{%endblock%}

<div class="container">

    <!--Left aside-->

    {%block aside%}


    <div class="top">
        <div class="logo">
            <a href="" class="">
                <span class="material-symbols-outlined">
                    monitoring
                </span>
            </a>
            <h3 class="text__muted">Excel<span class="danger">_Generator</span></h3>
        </div>
        <div class="close" id="btn-close">
            <img src="img/close.svg" alt="">
        </div>
    </div>

    <div class="sidebar">
        <a class="aside-link" href="">
            <span class="material-symbols-outlined">
                home
            </span>
            <h3 class="tittle-aside">Home</h3>
        </a>
        <a class="aside-link" href="">
            <span class="material-symbols-outlined">
                person
            </span>
            <h3 class="tittle-aside">Mis Estadisticas</h3>
        </a>
        {% if session['role'] != 'Analista' %}
            <a class="aside-link" href="">
                <span class="material-symbols-outlined">
                    groups
                </span>
                <h3 class="tittle-aside">Campaña</h3>
            </a>
        
        <a class="aside-link" href="">
            <span class="material-symbols-outlined">
                bar_chart_4_bars
            </span>
            <h3 class="tittle-aside">Reportes</h3>
        </a>
        {%endif%}
        <a class="aside-link" href="/auth/logout">
            <span class="material-symbols-outlined">
                logout
            </span>
            <h3 class="tittle-aside">Logout</h3>
        </a>
    </div>


    {%endblock%}

    <!-- End Left aside-->


    <!--MAIN-->
    {%block main%}

    <h3 class="wellcome__message">Wellcome, {{session['fullname']}}</h3>
    <div class="date">
        <input type="date" name="current-date" id="" value="{{session['fecha']}}" disabled>
    </div>

    <!--Dashboard cards-->

    <div class="container__cards">

        <div class="card">
            <span class="material-symbols-outlined">confirmation_number</span>
            <div class="middle">
                <div class="left">
                    <h3>Tickets</h3>
                    <h1 class="success">100 <h2 class="text__muted">/ 100</h2>
                    </h1>
                </div>
                <div class="progress">
                    <svg>
                        <circle class="primary" cx="38" cy="38" r="36" fill="blue" />
                    </svg>

                    <div class="number">
                        <p>100%</p>
                    </div>
                    <small class="text__muted">Diciembre</small>
                </div>
            </div>
        </div>

        {% if session['role'] != 'Analista' %}
        <div class="card">
          <span class="material-symbols-outlined">confirmation_number</span>
          <div class="middle">
            <div class="left">
              <h3>Campaña: {{session['campaign']}}</h3>
              <h1 class="success">100 <h2 class="text__muted">/ 100</h2></h1>
            </div>
            <div class="progress">
              <svg>
                <circle class="primary" cx="38" cy="38" r="36" fill="blue" />
              </svg>
              <div class="number">
                <p>100%</p>
              </div>
              <small class="text__muted">2023</small>
            </div>
          </div>
        </div>
      {% endif %}
      

        <div class="card">
            <span class="material-symbols-outlined">confirmation_number</span>
            <div class="middle">
                <div class="left">
                    <h3>Objetivo</h3>
                    <h1 class="success">100<h2 class="text__muted">/ 100</h2>
                    </h1>
                </div>
                <div class="progress">
                    <svg>
                        <circle class="primary" cx="38" cy="38" r="36" fill="blue" />
                    </svg>

                    <div class="number">
                        <p>100%</p>
                    </div>
                    <small class="text__muted">Alcanzado</small>
                </div>
            </div>
        </div>
    </div>

    <!--End Dashboard cards-->

    {%endblock%}

    <!--End Main-->
</div>


{{super()}}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    {%block tittle%} {%endblock%}
    <!-- <link rel="stylesheet" href="{{url_for('css', filename='style.css')}}"> -->

    <!--CSS customizado-->
    {%block styles%}

    {%endblock%}
    
    {% endblock %}
</head>

<body>

    <header class="">
        {% block navbar %}
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="/user/login">
                <img class="logo_sm" src="{{url_for('img', filename='logo.png')}} " alt="logo">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/user/login">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Reportes</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Opciones
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Campaña</a></li>
                      <li><a class="dropdown-item" href="#">Perfil</a></li>
                      <li><a class="dropdown-item" href='{{url_for("user.new_user")}}'>Crear Usuario</a></li>
                      <li><a class="dropdown-item" href=' {{url_for("user.get_users")}} '>Usuarios</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        {% endblock %}
    </header>

    <div class="container">
      <aside>
        {%block aside%}
  
        {%endblock%}
      </aside>
      <main class="">
          {% block main %}
          
          {% endblock %}
      </main>
    </div>

    <footer>
        {% block footer %}
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
              <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
              </a>
              <span class="mb-3 mb-md-0 text-body-secondary">Excel_Generator © 2023</span>
            </div>
        
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
              <li class="ms-3">

              </li>
              <li class="ms-3">

              </li>
              <li class="ms-3">

              </li>
            </ul>
          </footer>
        {% endblock %}
    </footer>
<script type="module" src='/js/app.mjs'></script>
<script src="/js/dashboard.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" 
crossorigin="anonymous"></script>
</body>
</html>

templates/sign_in.html
{%extends 'layout.html'%}

{% block head %}
    {% block tittle %}
    <title>Login User</title>
    {% endblock %}
    <!--Link boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
    <!--Boostrap customizado-->
    {%block styles%}
        <link rel="stylesheet" href="{{url_for('css', filename='styles_logo.css')}}">
    {%endblock%}
{% endblock %}

{% block main%}

<div class="container-fluid">

    <div class="row d-flex justify-content-center align-items-center py-5 my-2">

        <div class="col-lg-3 py-5 my-2">

            <div class="text-center">
                <img class="logo_sm img-fluid" src=" {{url_for('img', filename='logo.png')}} " alt="Logo">
            </div>

            <form action="/auth/login" method="POST" class="">
                <div class="input-group pb-2">
                    <span class="input-group-text" id="addon-wrapping">
                        <img src="{{url_for('img', filename='username_icon.svg')}}" alt="">
                    </span>
                    <input name="username" id="username" type="text" class="form-control input-login"
                        placeholder="Username" aria-label="username" aria-describedby="addon-wrapping"
                        pattern="[a-zA-Z0-9]+">

                    <label for="username"></label>
                </div>

                <div class="input-group pb-2">
                    <span class="input-group-text" id="addon-wrapping">
                        <img src="{{url_for('img', filename='pass_icon.svg')}}" alt="">
                    </span>
                    <input name="password" id="password" type="password" class="form-control input-login"
                        placeholder="Password" aria-label="password" aria-describedby="addon-wrapping">
                    <label for="password"></label>
                </div>

                <hr>

                <div class="d-flex justify-content-center">
                    <button id="login" class="btn btn-primary" type="submit">Login</button>
                </div>

            </form>

        </div>

    </div>
</div>

{% endblock %}
{{super()}}

templates/sign_up.html
{%extends 'layout.html'%}

{% block head %}
    {% block tittle %}
    <title>Create User</title>
    {% endblock %}
    <!--Link boostrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous">
    <!--Boostrap customizado-->
    {%block styles%}
        <link rel="stylesheet" href="{{url_for('css', filename='styles_logo.css')}}">
    {%endblock%}
{% endblock %}


{%block main%}

<div class="container">

    <form id="form_signup" class="my-2 mb-2" action="" method="POST">

        <div class="d-flex"> 
            <div class="input-group w-25 align-items-center justify-content-center ms-1 me-1 my-1 mb-1">
                <label for="ET">ET</label>
                <input id="ET" value="ET" class="w-25 input-signup" type="radio" name="prefijo"
                    data-tipo="type_employee" required>
            </div>
            <div class="input-group w-25 align-items-center justify-content-center ms-1 me-1 my-1 mb-1">
                <label for="AE">AE</label>
                <input id="AE" value="AE" class="w-25 input-signup" type="radio" name="prefijo"
                    data-tipo="type_employee" required>
            </div>
            <div class="input-group w-50 ms-1 me-1 my-1 mb-1">
                <span class="input-group-text" id="addon-wrapping">
                    <img src=" {{url_for('img', filename='employee_icon.svg')}} " alt="">
                </span>
                <input id="N° Empleado" name="num_employee" type="text" class="form-control" placeholder="N° Employee"
                    aria-label="id" aria-describedby="addon-wrapping" data-tipo="numemployee" required
                    pattern="^\d{5,6}$">
                <label for="N° Empleado"></label>
                <span class="error-false"></span>
            </div>
        </div>

        <div class="d-flex">
            <div class="input-group ms-1 me-1 my-1 mb-1">
                <span class="input-group-text" id="addon-wrapping">
                    <img src="{{url_for('img', filename='name_icon.svg')}}" alt="">
                </span>
                <input id="Nombre" name="first_name" type="text" class="form-control input-signup"
                    placeholder="First Name" aria-label="first_name" aria-describedby="addon-wrapping"
                    data-tipo="first_name" required pattern="^[a-zA-Z]{3,25}$">
                <label for="Nombre"></label>
                <span class="error-false"></span>
            </div>

            <div class="input-group ms-1 me-1 my-1 mb-1">
                <span class="input-group-text" id="addon-wrapping">
                    <img src="{{url_for('img', filename='name_icon.svg')}}" alt="">
                </span>
                <input id="Apellido" name="last_name" type="text" class="form-control" placeholder="Last Name"
                    aria-label="last_name" aria-describedby="addon-wrapping" data-tipo="last_name" required
                    pattern="^[a-zA-Z]{3,25}$">
                <label for="Apellido"></label>
                <span class="error-false"></span>
            </div>
        </div>

        <div class="d-flex">
            <div class="input-group ps-1 pe-1 py-1 pb-1 w-50">
                <span class="visibility input-group-text" id="addon-wrapping">
                    <img class="visibilityImg" src=" {{url_for('img', filename='visibility_icon.svg')}} " alt="">
                    <img class="invisibilityImg" src="{{url_for('img', filename='pass_icon.svg')}}" alt="">
                </span>
                <input id="Contraseña" name="password" type="password" class="form-control" placeholder="Password"
                    aria-label="password" aria-describedby="addon-wrapping" data-tipo="password" required
                    pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!?@#$%^&*()_+-]).{8,15}$">
                <label for="Contraseña"></label>
                <span class="error-false"></span>
            </div>

            <div class="input-group ps-1 pe-1 py-1 pb-1 w-50">
                <span class="visibility input-group-text" id="addon-wrapping">
                    <img id="" class="visibilityImg" src="{{url_for('img', filename='visibility_icon.svg')}}" alt="">
                    <img class="invisibilityImg" src="{{url_for('img', filename='pass_icon.svg')}}" alt="">

                </span>
                <input id="Confirmacion de contraseña" name="confirm-password" type="password" class="form-control"
                    placeholder="Confirm Password" aria-label="confirm-password" aria-describedby="addon-wrapping"
                    data-tipo="password" required
                    pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!?@#$%^&*()_+-]).{8,15}$">
                <label for="Confirmacion de contraseña"></label>
                <span class="error-false"></span>
            </div>
        </div>

        <div class="input-group ms-1 me-1 my-1 mb-1">
            <span class="input-group-text" id="addon-wrapping">
                <img src=" {{url_for('img', filename='user_icon.svg')}} " alt="">
            </span>
            <input id="Email" name="email" type="email" class="form-control input-login" placeholder="Email@example.com"
                aria-label="email" aria-describedby="addon-wrapping" data-tipo="email" required>
            <label for="Email"></label>
            <span class="error-false"></span>
        </div>


        <div class="d-flex">
            <div class="form-floating w-50 ms-1 me-1 my-1 mb-1">
                <select id="campaign" name="campaign" class="form-select input-signup" data-tipo="campaign" required>
                    <option selected disabled>Select a campaign</option>
                    <option value="1">UP</option>
                    <option value="2">ATH Movil</option>
                    <option value="3">Place to Pay</option>
                </select>
                <label for="campaign">Campaign</label>
            </div>

            <div class="form-floating w-50 ms-1 me-1 my-1 mb-1">
                <select id="role" name="role" class="form-select input-signup" data-tipo="role" required>
                    <option selected disabled>Select a role</option>
                    <option value="1">Analyst</option>
                    <option value="2">Supervisor</option>
                </select>
                <label for="role">Role</label>
            </div>
        </div>

        <hr>

        <div class="form-btn d-flex justify-content-end">
            <button id="submit_login" class="btn btn-primary" type="submit">Create User</button>
        </div>

    </form>
</div>

<div class="col-12 d-flex justify-content-center align-items-center">
    <span class="response" role="alert"></span>
</div>
{%endblock%}
{{super()}}